name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Substitua 'main' pelo nome da sua branch principal, se for diferente

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      # Adicione mais etapas conforme necessário, como construção do aplicativo e implantação
