name: CI

on:
  push:
    branches:
      - main   # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: windows-22
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Maven
      run: |
        sudo apt-get install -y maven
        mvn --version

    - name: Build with Maven
      run: mvn clean install

    # Adicione etapas adicionais conforme necessário para testar e implantar seu projeto Java.
